'use strict';

var CONSTANTS = module.exports;

// MESSAGE_QUEUES
CONSTANTS.MAIN_RENDER_LEDGER = "MAIN_RENDER_LEDGER"
CONSTANTS.MAIN_LEDGER_WORKER = "MAIN_LEDGER_WORKER"

// ACTIONS
CONSTANTS.FORWARD           = "FORWARD"
CONSTANTS.LEDGER_CONNECTION = "LEDGER_CONNECTION"
CONSTANTS.GET_ADDRESSES     = "GET_ADDRESSES"
CONSTANTS.SIGN_TRANSACTION  = "SIGN_TRANSACTION"
CONSTANTS.SIGN_MESSAGE      = "SIGN_MESSAGE"

module.exports = CONSTANTS;