'use strict';

var CONSTANTS = module.exports;

// MESSAGE_QUEUES
CONSTANTS.MAIN_RENDER_LEDGER = "MAIN_RENDER_LEDGER"

// ACTIONS
CONSTANTS.FORWARD           = "FORWARD"
CONSTANTS.STATE_CHANGE      = "STATE_CHANGE"
CONSTANTS.DETECT_LEDGER     = "DETECT_LEDGER"
CONSTANTS.GET_CONFIGURATION = "GET_CONFIGURATION"
CONSTANTS.GET_ADDRESSES     = "GET_ADDRESSES"
CONSTANTS.SIGN_TRANSACTION  = "SIGN_TRANSACTION"
CONSTANTS.SIGN_MESSAGE      = "SIGN_MESSAGE"

module.exports = CONSTANTS;