export enum StoreBinding {
	// Announcements
	AnnouncementsFetch = "announcements/fetch",
	AnnouncementsMarkAsRead = "announcements/markAsRead",
	AnnouncementsMarkAsReadBulk = "announcements/markAsReadBulk",
	// Application
	AppSetHasAcceptedBlacklistDisclaimer = "app/setHasAcceptedBlacklistDisclaimer",
	AppSetHasSeenIntroduction = "app/setHasSeenIntroduction",
	AppSetIsScreenshotProtectionEnabled = "app/setIsScreenshotProtectionEnabled",
	AppSetLatestAppliedMigration = "app/setLatestAppliedMigration",
	AppSetPinCode = "app/setPinCode",
	AppSetVotingExplanation = "app/setVotingExplanation",
	// Delegate
	DelegateLoad = "delegate/load",
	DelegateSet = "delegate/set",
	// Leder
	LedgerCacheWallets = "ledger/cacheWallets",
	LedgerClearWalletCache = "ledger/clearWalletCache",
	LedgerConnect = "ledger/connect",
	LedgerDisconnect = "ledger/disconnect",
	LedgerGetAddress = "ledger/getAddress",
	LedgerGetPublicKey = "ledger/getPublicKey",
	LedgerGetVersion = "ledger/getVersion",
	LedgerGetWallet = "ledger/getWallet",
	LedgerInit = "ledger/init",
	LedgerReloadWallets = "ledger/reloadWallets",
	LedgerReset = "ledger/reset",
	LedgerSetSlip44 = "ledger/setSlip44",
	LedgerSignMessage = "ledger/signMessage",
	LedgerSignTransaction = "ledger/signTransaction",
	LedgerUpdateVersion = "ledger/updateVersion",
	LedgerUpdateWallet = "ledger/updateWallet",
	LedgerUpdateWallets = "ledger/updateWallets",
	// Market
	MarketRefreshTicker = "market/refreshTicker",
	// Network
	NetworkAddCustomNetwork = "network/addCustomNetwork",
	NetworkFetchFees = "network/fetchFees",
	NetworkLoad = "network/load",
	NetworkRemoveCustomNetwork = "network/removeCustomNetwork",
	NetworkUpdate = "network/update",
	NetworkUpdateCustomNetwork = "network/updateCustomNetwork",
	NetworkUpdateData = "network/updateData",
	// Peer
	PeerClientServiceFromPeer = "peer/clientServiceFromPeer",
	PeerConnectToBest = "peer/connectToBest",
	PeerFindBest = "peer/findBest",
	PeerGetPeerDiscovery = "peer/getPeerDiscovery",
	PeerRefresh = "peer/refresh",
	PeerSet = "peer/set",
	PeerSetCurrentPeer = "peer/setCurrentPeer",
	PeerSetToNetwork = "peer/setToNetwork",
	PeerUpdateCurrentPeerStatus = "peer/updateCurrentPeerStatus",
	PeerValidatePeer = "peer/validatePeer",
	// Plugin
	PluginDeleteInstalled = "plugin/deleteInstalled",
	PluginDeleteLoaded = "plugin/deleteLoaded",
	PluginDeletePlugin = "plugin/deletePlugin",
	PluginDeletePluginOptionsForProfile = "plugin/deletePluginOptionsForProfile",
	PluginLoadPluginsForProfile = "plugin/loadPluginsForProfile",
	PluginLoadPluginsForProfiles = "plugin/loadPluginsForProfiles",
	PluginReset = "plugin/reset",
	PluginSetAvailable = "plugin/setAvailable",
	PluginSetAvatars = "plugin/setAvatars",
	PluginSetBlacklisted = "plugin/setBlacklisted",
	PluginSetEnabled = "plugin/setEnabled",
	PluginSetInstalled = "plugin/setInstalled",
	PluginSetLanguages = "plugin/setLanguages",
	PluginSetLoaded = "plugin/setLoaded",
	PluginSetMenuItems = "plugin/setMenuItems",
	PluginSetPluginOption = "plugin/setPluginOption",
	PluginSetThemes = "plugin/setThemes",
	PluginSetWalletTabs = "plugin/setWalletTabs",
	PluginSetWhitelisted = "plugin/setWhitelisted",
	// Profile
	ProfileCreate = "profile/create",
	ProfileDelete = "profile/delete",
	ProfileSetMultiSignaturePeer = "profile/setMultiSignaturePeer",
	ProfileUpdate = "profile/update",
	// Data
	ResetData = "resetData",
	// Session
	SessionLoad = "session/load",
	SessionReset = "session/reset",
	SessionSetBackground = "session/setBackground",
	SessionSetBackgroundUpdateLedger = "session/setBackgroundUpdateLedger",
	SessionSetBip39Language = "session/setBip39Language",
	SessionSetBroadcastPeers = "session/setBroadcastPeers",
	SessionSetContactSortParams = "session/setContactSortParams",
	SessionSetCurrency = "session/setCurrency",
	SessionSetDefaultChosenFee = "session/setDefaultChosenFee",
	SessionSetHideWalletButtonText = "session/setHideWalletButtonText",
	SessionSetIsAdvancedModeEnabled = "session/setIsAdvancedModeEnabled",
	SessionSetIsMarketChartEnabled = "session/setIsMarketChartEnabled",
	SessionSetLanguage = "session/setLanguage",
	SessionSetLastFeeByType = "session/setLastFeeByType",
	SessionSetLedgerCache = "session/setLedgerCache",
	SessionSetMarketChartOptions = "session/setMarketChartOptions",
	SessionSetMultiSignaturePeer = "session/setMultiSignaturePeer",
	SessionSetPluginManagerLayout = "session/setPluginManagerLayout",
	SessionSetPluginMenuOpen = "session/setPluginMenuOpen",
	SessionSetPluginSortParams = "session/setPluginSortParams",
	SessionSetPriceApi = "session/setPriceApi",
	SessionSetProfileId = "session/setProfileId",
	SessionSetScreenshotProtection = "session/setScreenshotProtection",
	SessionSetTheme = "session/setTheme",
	SessionSetTimeFormat = "session/setTimeFormat",
	SessionSetTransactionTableRowCount = "session/setTransactionTableRowCount",
	SessionSetUnconfirmedVotes = "session/setUnconfirmedVotes",
	SessionSetWalletLayout = "session/setWalletLayout",
	SessionSetWalletSidebarFilters = "session/setWalletSidebarFilters",
	SessionSetWalletSidebarSortParams = "session/setWalletSidebarSortParams",
	SessionSetWalletSortParams = "session/setWalletSortParams",
	// Transaction
	TransactionClearUnconfirmedVotes = "transaction/clearUnconfirmedVotes",
	TransactionCreate = "transaction/create",
	TransactionDelete = "transaction/delete",
	TransactionDeleteBulk = "transaction/deleteBulk",
	TransactionProcessVotes = "transaction/processVotes",
	TransactionUpdateStaticFees = "transaction/updateStaticFees",
	UpdaterSetAvailableRelease = "updater/setAvailableRelease",
	// Wallet
	WalletAddSignedMessage = "wallet/addSignedMessage",
	WalletCreate = "wallet/create",
	WalletDelete = "wallet/delete",
	WalletDeleteSignedMessage = "wallet/deleteSignedMessage",
	WalletSetSecondaryButtonsVisible = "wallet/setSecondaryButtonsVisible",
	WalletUpdate = "wallet/update",
}
