import { BigNumber } from "@arkecosystem/platform-sdk-support";

export const networks = [
	{
		name: "Ark",
		isSelected: true,
	},
	{
		name: "Ethereum",
		isSelected: true,
	},
	{
		name: "Bitcoin",
		isSelected: false,
	},
];

export const wallets = [
	{
		id: "2ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		coinIcon: "Ethereum",
		coinClass: "text-theme-neutral-800 border-theme-neutral-600",
		address: "2ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		walletName: "My Eth",
		balance: "100,150 ETH",
		fiat: "1,000,000 USD",
		walletTypeIcons: ["Star", "Ledger"],
		actions: [
			{
				label: "Action 1",
				value: "1",
			},
			{
				label: "Action 2",
				value: "2",
			},
			{
				label: "Action 3",
				value: "3",
			},
		],
	},
	{
		id: "3ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		coinIcon: "Bitcoin",
		coinClass: "text-theme-warning-400 border-theme-warning-200",
		address: "3ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		walletName: "My Wallet",
		balance: "100 BTC",
		fiat: "1,000,000 USD",
		walletTypeIcons: ["Ledger"],
		actions: [
			{
				label: "Action 1",
				value: "1",
			},
			{
				label: "Action 2",
				value: "2",
			},
			{
				label: "Action 3",
				value: "3",
			},
		],
	},
	{
		id: "4ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		coinIcon: "Bitcoin",
		coinClass: "text-theme-warning-400 border-theme-warning-200",
		address: "4ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		walletName: "My Wallet",
		balance: "100 BTC",
		fiat: "1,000,000 USD",
		walletTypeIcons: ["Star"],
		actions: [
			{
				label: "Action 1",
				value: "1",
			},
			{
				label: "Action 2",
				value: "2",
			},
			{
				label: "Action 3",
				value: "3",
			},
		],
	},
	{
		id: "5ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		coinIcon: "Bitcoin",
		coinClass: "text-theme-warning-400 border-theme-warning-200",
		address: "5ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		walletName: "My Wallet",
		balance: "100 BTC",
		fiat: "1,000,000 USD",
		walletTypeIcons: ["Star", "Multisig", "Ledger"],
		actions: [
			{
				label: "Action 1",
				value: "1",
			},
			{
				label: "Action 2",
				value: "2",
			},
			{
				label: "Action 3",
				value: "3",
			},
		],
	},
	{
		id: "ac38fe6d-4b67-4ef1-85be-17c5f6841129",
		coinIcon: "Ark",
		coinClass: "text-theme-danger-400 border-theme-danger-light",
		address: "D61mfSggzbvQgTUe6JhYKH2doHaqJ3Dyib",
		walletName: "My Wallet",
		balance: "2,000,000 ARK",
		fiat: "1,000,000 USD",
		walletTypeIcons: ["Star", "Multisig", "Ledger"],
		actions: [
			{
				label: "Action 1",
				value: "1",
			},
			{
				label: "Action 2",
				value: "2",
			},
			{
				label: "Action 3",
				value: "3",
			},
		],
	},
	{
		id: "7ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		coinIcon: "Ethereum",
		coinClass: "text-theme-neutral-800 border-theme-neutral-600",
		address: "7ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		walletName: "My Eth",
		balance: "100,150 ETH",
		fiat: "1,000,000 USD",
		walletTypeIcons: ["Star", "Multisig", "Ledger"],
		actions: [
			{
				label: "Action 1",
				value: "1",
			},
			{
				label: "Action 2",
				value: "2",
			},
			{
				label: "Action 3",
				value: "3",
			},
		],
	},
	{
		isBlank: true,
		blankTitle: "You have 8 more wallets",
		blankTitleClass: "text-theme-neutral-dark cursor-pointer",
		blankSubtitle: "Look all wallet",
		blankSubtitleClass: "text-theme-primary font-semibold cursor-pointer",
	},
	{
		id: "8ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		coinIcon: "Bitcoin",
		coinClass: "text-theme-warning-400 border-theme-warning-200",
		address: "8ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		walletName: "My Wallet",
		balance: "100 BTC",
		fiat: "1,000,000 USD",
		walletTypeIcons: ["Star", "Multisig", "Ledger"],
		actions: [
			{
				label: "Action 1",
				value: "1",
			},
			{
				label: "Action 2",
				value: "2",
			},
			{
				label: "Action 3",
				value: "3",
			},
		],
	},
	{
		id: "9ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		coinIcon: "Bitcoin",
		coinClass: "text-theme-warning-400 border-theme-warning-200",
		address: "9ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		walletName: "My Wallet",
		balance: "100 BTC",
		fiat: "1,000,000 USD",
		walletTypeIcons: ["Star", "Multisig", "Ledger"],
		actions: [
			{
				label: "Action 1",
				value: "1",
			},
			{
				label: "Action 2",
				value: "2",
			},
			{
				label: "Action 3",
				value: "3",
			},
		],
	},
	{
		id: "ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		coinIcon: "Bitcoin",
		coinClass: "text-theme-warning-400 border-theme-warning-200",
		address: "ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		walletName: "My Wallet",
		balance: "100 BTC",
		fiat: "1,000,000 USD",
		walletTypeIcons: ["Star", "Multisig", "Ledger"],
		actions: [
			{
				label: "Action 1",
				value: "1",
			},
			{
				label: "Action 2",
				value: "2",
			},
			{
				label: "Action 3",
				value: "3",
			},
		],
	},
	{
		id: "10ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		coinIcon: "Bitcoin",
		coinClass: "text-theme-warning-400 border-theme-warning-200",
		address: "10ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		walletName: "My Wallet",
		balance: "100 BTC",
		fiat: "1,000,000 USD",
		walletTypeIcons: ["Star", "Multisig", "Ledger"],
		actions: [
			{
				label: "Action 1",
				value: "1",
			},
			{
				label: "Action 2",
				value: "2",
			},
			{
				label: "Action 3",
				value: "3",
			},
		],
	},
];

// Transaction History data
export const transactions = [
	{
		id: () => "ee4175091d9f4dacf5fed213711c3e0e4cc371e37afa7bce0429d09bcf3ecefe",
		type: () => "transfer",
		timestamp: () => 1596213281,
		confirmations: () => BigNumber.make(10),
		votes: () => ["10"],
		unvotes: () => ["10"],
		sender: () => "ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		recipient: () => "ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		recipients: () => [],
		amount: () => BigNumber.make(100),
		fee: () => BigNumber.make(21),
		memo: () => "Test",
		asset: () => ({ a: "b" }),
		isSent: () => true,
		isReceived: () => false,
		isTransfer: () => true,
		isSecondSignature: () => false,
		isMultiSignature: () => false,
		isDelegateRegistration: () => false,
		isDelegateResignation: () => false,
		isVote: () => false,
		isUnvote: () => false,
		isIpfs: () => false,
		isMultiPayment: () => false,
		isBusinessRegistration: () => false,
		isBusinessResignation: () => false,
		isBusinessUpdate: () => false,
		isBridgechainRegistration: () => false,
		isBridgechainResignation: () => false,
		isBridgechainUpdate: () => false,
		isEntityRegistration: () => false,
		isEntityResignation: () => false,
		isEntityUpdate: () => false,
		isHtlcLock: () => false,
		isHtlcClaim: () => false,
		isHtlcRefund: () => false,
		toObject: () => ({ a: "b" }),
		hasPassed: () => true,
		hasFailed: () => false,
		getMeta: () => "",
		setMeta: () => "",
	},
	{
		id: () => "ee4175091d9f4dacf5fed213711c3e0e4cc371e37afa7bce0429d09bcf3ecefe",
		type: () => "transfer",
		timestamp: () => 1596213281,
		confirmations: () => BigNumber.make(5),
		votes: () => ["10"],
		unvotes: () => ["10"],
		sender: () => "ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		recipient: () => "ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		recipients: () => [],
		amount: () => BigNumber.make(52),
		fee: () => BigNumber.make(0.2),
		memo: () => "Test",
		asset: () => ({ a: "b" }),
		isSent: () => true,
		isReceived: () => false,
		isTransfer: () => true,
		isSecondSignature: () => true,
		isMultiSignature: () => false,
		isDelegateRegistration: () => false,
		isDelegateResignation: () => false,
		isVote: () => false,
		isUnvote: () => false,
		isIpfs: () => false,
		isMultiPayment: () => false,
		isBusinessRegistration: () => false,
		isBusinessResignation: () => false,
		isBusinessUpdate: () => false,
		isBridgechainRegistration: () => false,
		isBridgechainResignation: () => false,
		isBridgechainUpdate: () => false,
		isEntityRegistration: () => false,
		isEntityResignation: () => false,
		isEntityUpdate: () => false,
		isHtlcLock: () => false,
		isHtlcClaim: () => false,
		isHtlcRefund: () => false,
		toObject: () => ({ a: "b" }),
		hasPassed: () => true,
		hasFailed: () => false,
		getMeta: () => "",
		setMeta: () => "",
	},
	{
		id: () => "ee4175091d9f4dacf5fed213711c3e0e4cc371e37afa7bce0429d09bcf3ecefe",
		type: () => "vote",
		timestamp: () => 1596213281,
		confirmations: () => BigNumber.make(5),
		votes: () => ["10"],
		unvotes: () => ["10"],
		sender: () => "ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		recipient: () => "ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		recipients: () => [],
		amount: () => BigNumber.make(1),
		fee: () => BigNumber.make(0.2),
		memo: () => "Test",
		asset: () => ({ a: "b" }),
		isSent: () => true,
		isReceived: () => false,
		isTransfer: () => true,
		isSecondSignature: () => true,
		isMultiSignature: () => false,
		isDelegateRegistration: () => false,
		isDelegateResignation: () => false,
		isVote: () => true,
		isUnvote: () => false,
		isIpfs: () => false,
		isMultiPayment: () => false,
		isBusinessRegistration: () => false,
		isBusinessResignation: () => false,
		isBusinessUpdate: () => false,
		isBridgechainRegistration: () => false,
		isBridgechainResignation: () => false,
		isBridgechainUpdate: () => false,
		isEntityRegistration: () => false,
		isEntityResignation: () => false,
		isEntityUpdate: () => false,
		isHtlcLock: () => false,
		isHtlcClaim: () => false,
		isHtlcRefund: () => false,
		toObject: () => ({ a: "b" }),
		hasPassed: () => true,
		hasFailed: () => false,
		getMeta: () => "",
		setMeta: () => "",
	},
	{
		id: () => "ee4175091d9f4dacf5fed213711c3e0e4cc371e37afa7bce0429d09bcf3ecefe",
		type: () => "delegateRegistration",
		timestamp: () => 1596213281,
		confirmations: () => BigNumber.make(5),
		votes: () => ["10"],
		unvotes: () => ["10"],
		sender: () => "ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		recipient: () => "ASuusXSW9kfWnicScSgUTjttP6T9GQ3kqT",
		recipients: () => [],
		amount: () => BigNumber.make(1),
		fee: () => BigNumber.make(0.2),
		memo: () => "Test",
		asset: () => ({ a: "b" }),
		isSent: () => true,
		isReceived: () => false,
		isTransfer: () => true,
		isSecondSignature: () => true,
		isMultiSignature: () => false,
		isDelegateRegistration: () => true,
		isDelegateResignation: () => false,
		isVote: () => true,
		isUnvote: () => false,
		isIpfs: () => false,
		isMultiPayment: () => false,
		isBusinessRegistration: () => false,
		isBusinessResignation: () => false,
		isBusinessUpdate: () => false,
		isBridgechainRegistration: () => false,
		isBridgechainResignation: () => false,
		isBridgechainUpdate: () => false,
		isEntityRegistration: () => false,
		isEntityResignation: () => false,
		isEntityUpdate: () => false,
		isHtlcLock: () => false,
		isHtlcClaim: () => false,
		isHtlcRefund: () => false,
		toObject: () => ({ a: "b" }),
		hasPassed: () => true,
		hasFailed: () => false,
		getMeta: () => "",
		setMeta: () => "",
	},
];

export const portfolioPercentages = [
	{
		label: "ARK",
		value: 40,
		color: "danger-500",
	},
	{
		label: "BTC",
		value: 25,
		color: "warning-500",
	},
	{
		label: "ETH",
		value: 20,
		color: "primary-500",
	},
	{
		label: "Other",
		value: 15,
		color: "neutral-400",
	},
];

export const balances = [
	{ name: "Mon", label: "22 Jun, 2020", usd: 1000, btc: 2400, formatted: { usd: "1,000", btc: "0.26" } },
	{ name: "Tue", label: "23 Jun, 2020", usd: 3000, btc: 5400, formatted: { usd: "3,000", btc: "0.58" } },
	{ name: "Wed", label: "24 Jun, 2020", usd: 15100, btc: 1398, formatted: { usd: "15,100", btc: "0.15" } },
	{ name: "Thu", label: "25 Jun, 2020", usd: 4000, btc: 9800, formatted: { usd: "4,000", btc: "1.06" } },
	{ name: "Fri", label: "26 Jun, 2020", usd: 11200, btc: 2000, formatted: { usd: "11,200", btc: "0.22" } },
	{ name: "Sat", label: "27 Jun, 2020", usd: 3000, btc: 4800, formatted: { usd: "3,000", btc: "0.52" } },
	{ name: "Sun", label: "28 Jun, 2020", usd: 8000, btc: 18000, formatted: { usd: "8,000", btc: "2.16" } },
];
